# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Catalyst-Plugin-Captcha
version:      0.01
version_from: lib/Catalyst/Plugin/Captcha.pm
installdirs:  site
requires:
    Catalyst:                      5.3
    Catalyst::Plugin::Session:     0
    GD::SecurityImage:             0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
